apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-3
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    env:
      - name: SPRING_PROFILE
        value: prod

      - name: DB_USER
        valueFrom:
          secretKeyRef: