apiVersion: v1
kind: Pod
metadata:
  name: mynewpod
  labels:
    tier: backend
spec:
  containers:
    - name: nginx-container
      image: nginx
      envFrom:
        - secretRef:
            name: app-secret

      #OR
      env:
        - name: DB_Password
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_Password