apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_HOST: mysql   # encode using command: echo -n 'mysql' | base64  and decode using: echo -n 'mysql' | base64 decode
  DB_USER: root
  DB_Password: passwrd